---
title: "Codealong_5"
author: "Jake Nyiri"
date: "11/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(palmerpenguins)
library(effsize)
library(broom)
library(ggbeeswarm)
library(car)
```
#T-TEST 1

```{r}
#compoare mass between male/female chinstrap penguins

chinstrap_penguins <- penguins %>% 
  filter(species == "Chinstrap")

#basic histogram of masses
chin_hist <- chinstrap_penguins %>% 
  ggplot(aes(x = body_mass_g))+
  geom_histogram(bins = 10)+
  facet_wrap(~sex)

chin_hist

#Do a qq plot to explore normality

chin_qq <- chinstrap_penguins %>% 
  ggplot(aes(sample = body_mass_g))+
  geom_qq()+
  facet_wrap(~sex)

chin_qq

```
```{r}
#get descriptive stats of chinstraps

chin_stat <- chinstrap_penguins %>% 
  group_by(sex) %>% 
  summarize(
    mean = mean(body_mass_g),
    median = median(body_mass_g),
    sd = sd(body_mass_g),
    sample_size = n())


chin_stat

```

```{r}
#Going to do a t-tst or anova or some shit
#Firwt get vectors of mass for m/f chinstraps to ue t-test

male_chinstrap_mass <-chinstrap_penguins %>% 
  filter(sex == "female") %>% 
  pull(body_mass_g)

female_chinstrap_mass <- chinstrap_penguins %>%
  filter(sex == "male") %>% 
  pull(body_mass_g)

###do the tests

#IS there sig dif in the masses?
chinstrap_test <- 
  t.test(male_chinstrap_mass, female_chinstrap_mass)

chinstrap_test

#cohen d effect size time!
chinstrap_cohen<-
  cohen.d(male_chinstrap_mass, female_chinstrap_mass)

chinstrap_cohen

#Are male cp sign. larger than fem. peng?
#Is one-sided test, could I have gotten 'this large' or greater of difference by random sample (Not 'this distance away')

chinstrap_size_compare<-t.test(female_chinstrap_mass,male_chinstrap_mass, alternative = "greater") #must line up with order of arguments (is male greater than female)
#This is backwards! Not sure why--in codealong video these are reversed and it works! WHy is my test running backwards?


chinstrap_size_compare

```
```{r}
#One way anova

#MAke table of penguin counts by species and sex

penguin_counts <- penguins %>% 
  count(species, sex)

penguin_counts

#make subset of only f penguins

penguin_f <- penguins %>% 
  filter(sex == "female")

peng_plot <- penguin_f %>% 
  ggplot(aes(x=flipper_length_mm))+
  geom_histogram(aes(fill = species))+
 facet_wrap(~species, scales = "free") #this lets each one have its own x, y axis scale

peng_plot

#Check normality with qq
peng_plot_q <- penguin_f %>% 
  ggplot(aes(sample=flipper_length_mm))+
  geom_qq(aes(color = species))+
 facet_wrap(~species, scales = "free")

peng_plot_q
```
```{r}
#Summary stats for pengs

peng_summary<-penguin_f %>% 
  group_by(species) %>% 
  summarize(
    mean_flip = mean(flipper_length_mm),
    sd_flip = sd(flipper_length_mm),
    sample_size = n(),
    variance = var(flipper_length_mm),
    std_error = (sd_flip / sqrt(sample_size)))


peng_summary

#levene test is hypoth test where null is groups have = variance

leveneTest(flipper_length_mm ~ species, data=penguin_f)

```

```{r}
#Make beeswarm plot with mean +/- 1 std dev

ggplot()+
  geom_beeswarm(data = penguin_f, 
                aes(x=species, y=flipper_length_mm),
                color="gray70",
                size = 3,
                alpha = 0.5) + #changes transparency
  geom_point(data = peng_summary, 
             aes(x=species, y=mean_flip),
                  size=4)+
  geom_errorbar(data = peng_summary,
                aes(x=species,
                    ymax=mean_flip + sd_flip,
                    ymin = mean_flip - sd_flip,
                    width = 0.1))
                 
```

```{r}
#Now actual anova

peng_aov <- aov(flipper_length_mm~species, data=penguin_f)
summary(peng_aov)

TukeyHSD(peng_aov)

#Do a type 3 anova becuase that's what you use if your sample set isn't balanced (different smaple sizes etc) ype 1 is aov, best for same sample sizes across factors.

peng_linear_model <- lm(flipper_length_mm ~ species, data=penguin_f)
peng_aov_t3 <- Anova(peng_linear_model, type = "III")
peng_aov_t3

```


